services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: job_finder
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - database_data:/var/lib/mysql
  ###< doctrine/doctrine-bundle ###